#! /bin/bash

CURRENT_YEAR=$(date +%Y)
CURRENT_MONTH=$(date +%m)
CURRENT_DAY=$(date +%d)
CURRENT_TIME=$(date +%H%M)
CURRENT_HOUR=$(date +%H)
CURRENT_MINUTE=$(date +%M)
CURRENT_ISO8601=$(date +"%Y-%m-%dT%H:%M:%S%z")
DIR="./content/journal/$CURRENT_YEAR/$CURRENT_MONTH/$CURRENT_DAY"
FILENAME="$CURRENT_TIME.md"
FILEPATH="$DIR/$FILENAME"
DESCRIPTION=""
TITLE="$CURRENT_YEAR-$CURRENT_MONTH-$CURRENT_DAY, $CURRENT_HOUR:$CURRENT_MINUTE"

if [ -n "$1" ]; then
  TITLE="$1"
fi

# LOCATION CHECK
# Check to see if in root of repo
# If not:
# echo "Needs to be run in the root of the project repo."

# MARKDOWN
echo "Creating $FILEPATH"
mkdir -p $DIR
touch $FILEPATH

cat << EOF > $FILEPATH
---
title: $TITLE
date: "$CURRENT_ISO8601"
---

$DESCRIPTION

EOF

code $FILEPATH
